### ISSUE TITLE
Suggest ordering of the elements

### ISSUE THREAD

**Issue by davide-f** [oxinabox/LayeredLayouts.jl#12]
Dear @oxinabox ,
It would be interesting to possibly specify the ordering of the elements in the layout, and this issue follows your recommendation on SankeyPlots.jl.
This would be in handy in SankeyPlots for example, to possibly order the boxes: i.e. leave the boxes with the same color on the same row.
I attach a picture.
![image](https://user-images.githubusercontent.com/67809479/109789676-ddf3de80-7c10-11eb-96d5-736b01d22eee.png)
Thank you

**Comment by oxinabox** [comment]
So when working out the ordering we solve a constrained mixed integer linear optimization problem to minimize number if crossings.
It is around like 170 here:
https://www.github.com/oxinabox/LayeredLayouts.jl/tree/main/src%2Fzarate.jl

So some how we want to let the user add an additional factor in here I guess.
Something which says at least "all other things being equal, also maintain this order."

**Comment by davide-f** [comment]
Solved by #19
