### ISSUE TITLE
Specify the level of the input

### ISSUE THREAD

**Issue by davide-f** [oxinabox/LayeredLayouts.jl#13]
Dear @oxinabox ,
Another interesting improvement would be to specify the level where a given item should be placed.
In the example on SankeyPlots, it would be interesting to possibly specify that the blue box in the middle could be placed in the third column, rather than the second one.
I attach a picture as an example.
![image](https://user-images.githubusercontent.com/67809479/109790075-46db5680-7c11-11eb-9afb-f86d8637d2b8.png)
Thank you,
Davide

**Comment by oxinabox** [comment]
This is the layer assignment problem.
Right now our algorithm for that is very simple.
It just puts everything into a layer given by the length of the longest path from any root vertex (one with no incoming connections)

Possibly we can let the user pass in a layer assignment method.
Including one that assigns some nodes to a particular layer, and then works out the rest?

As a hack you could insert fake nodes into the graph to push things right, and then remove them before plotting.
(That's what the algorithm does in general when there is a connection that spans multiple layers)

**Comment by davide-f** [comment]
It would be nice to possibly add an optional element to specify the position of some of the elements; maybe a dict to let specify only a selected number of options or a vector for everyone.

Thank for the temporarily hack, I'll see if I really need to implement it or I look for the final version

**Comment by davide-f** [comment]
I successfully obtained the following result with little changes of the layer assigning methodology (yet with some assumption to simplify the problem)
![image](https://user-images.githubusercontent.com/67809479/115549023-72410000-a2a8-11eb-8b8c-dd2d7851c1b7.png)
I add a pull request to show the changes

**Comment by davide-f** [comment]
Close via #17
