### ISSUE TITLE
PNGs missing from Readme

### ISSUE THREAD

**Issue by cormullion** [oxinabox/LayeredLayouts.jl#29]
I can't see the`tiny_depgraph.png` images in the Readme:

<img width="1121" alt="Screenshot 2023-02-23 at 10 51 27" src="https://user-images.githubusercontent.com/52289/220886541-683b7528-96ee-43a5-94cd-76bff54e2fa0.png">

The Markdown is:

```markdown
![tiny_depgraph](./test/references/Zarate/direct/tiny_depgraph.png 
 "tiny_depgraph") | ![tiny_depgraph](./test/references/Zarate/paths/tiny_depgraph.png "d") |
```

**Comment by oxinabox** [comment]
they all seem to be there for me

**Comment by thchr** [comment]
The references in the top row of the table are gone, i.e., the references to
`./test/references/Zarate/direct/tiny_depgraph.png` and `./test/references/Zarate/paths/tiny_depgraph.png` were missing.

It seems `tiny_depgraph` got accidentally removed in https://github.com/oxinabox/LayeredLayouts.jl/pull/25. I've readded them as an unrelated part of #31.
