### ISSUE TITLE
Force equal positions for nodes in identical layers

### ISSUE THREAD

**Issue by thchr** [oxinabox/LayeredLayouts.jl#30]
First: thanks for a brilliant package @oxinabox - it's been extremely helpful to me lately..!

Next: I have use case where I want to enforce that certain nodes in _distinct_ layers share the same ordering. Below is an example:
<img src=https://user-images.githubusercontent.com/26799210/222434475-d5a47653-1294-47cf-ab67-a4743767f98a.png width=500>
Here, I would want to constrain the orderings between nodes in layers with the same overall label (e.g., Γ) to have the same ordering of the nodes in each. In the example above, I would want the colors to be ordered identically (and ideally, to have the same y-values) in the two layers. In my example here, similar constraints apply to e.g. the H, Δ, and Λ layers.

To that end, two questions:
1. What would be a good interface for this?
   One option would be to e.g. have something like `force_equal :: Vector{Pair{Int, Int}}` which forces the y-positions of the vertices in each pair to be identical. I don't know if this is compatible with the implementation though, because this does not express an ordering per se.
2. How to best implement something like this? From my not-so-complete understanding of the algorithm, it seems it should be done by imposing a constraint of an identical ordering between layers - and then maybe afterwards equating the y-positions? Is there a more direct path?

I'd be very happy to add it to the package if I could get a bit of guidance on how to approach it.

**Comment by thchr** [comment]
I wrote a possible implementation [here](https://github.com/oxinabox/LayeredLayouts.jl/compare/main...thchr:LayeredLayouts.jl:equal_layers?expand=1), which allows forcing all the nodes in different layers to have the same y-coordinate. Seems to work well.

In principle, it could be nice to have more fine-grained control, e.g. to only link certain nodes or to link in a specified order. That would require a more complicated API though.

Let me know if something like the linked or similar would be welcome; if so, I'll turn it into a PR.

**Comment by oxinabox** [comment]
I think this feature does make sense yes, can you open a PR and we can discuss details there?
SOrry I am very busy and will continue to be slow to respond

**Comment by thchr** [comment]
Closed by #31.
