### ISSUE TITLE
Inexact Error in Zarate Algorithm

### ISSUE THREAD

**Issue by atiyabzafar** [oxinabox/LayeredLayouts.jl#33]
First of all thanks for this library. I have been using NetworkLayouts.jl for almost a year but the Stress Layout was enough for my work. 
Recently I was in need of a hierarchical layout and found your repository.

I have found this error in a few graphs I have been trying to visualize. I am not sure why this error is appearing. There is some Float value that the algorithm is calculating which because of floating point error is not rounding off to 1 and thus Julia is having trouble understanding that as a boolean variable.
The error with important trace:

```
InexactError: Bool(0.9999999999999152)
Stacktrace:
  [8] sort!
    @ ./sort.jl:661 [inlined]
  [9] #sort!#8
    @ ./sort.jl:722 [inlined]
 [10] order_layers!
    @ ~/.julia/packages/LayeredLayouts/bZiaV/src/zarate.jl:203 [inlined]
 [11] solve_positions(layout::Zarate, original_graph::SimpleDiGraph{Int8}; force_layer::Vector{Pair{Int64, Int64}}, force_order::Vector{Pair{Int64, Int64}})
    @ LayeredLayouts ~/.julia/packages/LayeredLayouts/bZiaV/src/zarate.jl:93
 [12] solve_positions(layout::Zarate, original_graph::SimpleDiGraph{Int8})
    @ LayeredLayouts ~/.julia/packages/LayeredLayouts/bZiaV/src/zarate.jl:65
```

I am attaching the graph that is causing the error for recreating. 
[example_graph.zip](https://github.com/oxinabox/LayeredLayouts.jl/files/11288192/example_graph.zip)

**Comment by oxinabox** [comment]
Can you try out the branch in #34 and confirm it solves your problem?
do this via 
`] add LayeredLayouts#ox/round`
